variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build_and_deploy

deploy:
  stage: build_and_deploy
  environment:
    name: server
  services: 
    - docker:dind
    - maven
  tags:
    - spring_modules
  variables:
    #DOCKER_HOST: tcp://docker:2376/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - df
    - cat /etc/resolv.conf
    - cat /etc/hosts
  script:
    - apk add nmap
    - nmap -sT -p- docker
    - mvn clean package -DskipTests=true
    - docker compose up
    