variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

image: maven:3.8.5-openjdk-17

deploy:
  stage: deploy
  tags: 
    - spring_modules
  before_script:
    - apk update && apk add make
  script:
    - uname -a
    - whoami
    - make up
