variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

tags:
  - spring_modules

stages:
  - build
  - deploy

build:
  stage: build
  image: maven
  script:
   - mvn clean package -DskipTests=true

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  #enviroment:
