variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA


stages:
  - build
  - deploy

build:
  stage: build
  image: maven
  tags:
    - spring_modules
  script:
   - mvn clean package -DskipTests=true

deploy:
  stage: deploy
  environment:
    name: server
  tags:
    - spring_modules
    before_script:
    - df
    - cat /etc/resolv.conf
    - cat /etc/hosts
  script:
    - docker-compose up -d