variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy

build:
  stage: build
  image: maven
  tags:
    - spring_modules
  script:
   - mvn clean package -DskipTests=true

deploy:
  stage: deploy
  environment:
    name: server
  services: 
    - docker:dind
  tags:
    - spring_modules
  variables:
    DOCKER_HOST: tcp://docker:2376/
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - df
    - cat /etc/resolv.conf
    - cat /etc/hosts
  script:
    - apk add nmap
    - nmap -sT -p- docker
    - docker compose up
    