variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

image: docker
services:
  - docker:dind

deploy:
  stage: deploy
  tags: 
    - spring_modules
  before_script:
    - apk update && apk add make
    - apk add maven && apk add openjdk17
  script:
    - uname -a
    - whoami
    - java --version
    - make up
