variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - publish 

publish-docker:
  stage: publish
  tags: spring_modules
  image: docker
  services:
    - docker:dind
  script:
    - uname -a
    - whoami
    - make up
