version: "3.9"

services:
  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379

  client:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile_client
    ports:
      - 8080:80

  report:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile_report
    ports:
      - 8081:80
#
#  entry-point:
#    depends_on:
#      - client
#      - report
#    image: nginx
#    ports:
#     - 80:80
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
#