FROM maven

COPY Report/src /home/app/src
COPY Report/pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package -DskipTests=true

RUN ls -app

FROM openjdk:17

COPY /home/app/target/Report.jar application.jar

ENTRYPOINT ["java", "-jar", "application.jar"]