FROM maven

COPY Client/src /home/app/src
COPY Client/pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package -DskipTests=true

RUN ls -a

COPY /home/app/target/Client.jar application.jar

ENTRYPOINT ["java", "-jar", "application.jar"]