version: "3.9"

services:
  redis:
    container_name: redis-service
    image: redis:latest
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379

  client:
    container_name: client
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile_client
    ports:
      - 8082:80

  report:
    container_name: report
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile_report
    ports:
      - 8083:80

  entry-point:
    depends_on:
      - client
      - report
    image: nginx
    ports:
     - 8093:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
