FROM maven AS build

COPY Client/src /home/app/src
COPY Client/pom.xml /home/app

RUN ls -a

RUN mvn -f /home/app/pom.xml clean package -DskipTests=true

FROM openjdk:17

COPY --from=build /home/app/target/Client.jar application.jar

ENTRYPOINT ["java", "-jar", "application.jar"]